# Generated by Django 5.2.4 on 2025-07-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_year', models.IntegerField()),
                ('salary', models.FloatField()),
                ('salary_currency', models.CharField(max_length=10)),
                ('salary_in_usd', models.FloatField()),
                ('remote_ratio', models.IntegerField()),
                ('company_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='job_record.country')),
                ('company_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_record.companysize')),
                ('employee_residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residences', to='job_record.country')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_record.employmenttype')),
                ('experience_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_record.experiencelevel')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_record.jobtitle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work_year', 'job_title', 'employee_residence', 'company_location', 'salary_in_usd'), name='unique_job_record')],
            },
        ),
    ]
