# Generated by Django 5.2.4 on 2025-07-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_record', '0002_candidate_contract_industry_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrecord',
            name='contract',
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_record.industry'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_records', to='job_record.contract'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_records', to='job_record.candidate'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='company_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='company_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='employee_residence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='experience_level',
            field=models.CharField(choices=[('EN', 'Entry-level'), ('MI', 'Mid-level'), ('SE', 'Senior-level'), ('EX', 'Executive-level')], max_length=2),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='remote_ratio',
            field=models.PositiveSmallIntegerField(help_text='Percentage of remote work (0-100)'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='salary_in_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='skills',
            field=models.ManyToManyField(related_name='candidates', to='job_record.skill'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='Contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_record.contract'),
        ),
    ]
