# Generated by Django 5.2.4 on 2025-07-08 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_reccord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='company_size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='employee_residence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='company_location',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='jobrecord',
            name='employment_type',
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='experience_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='job_title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveConstraint(
            model_name='jobrecord',
            name='unique_job_record',
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='work_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_reccord.candidate'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_reccord.contract'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_reccord.industry'),
        ),
        migrations.AddField(
            model_name='jobrecord',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job_reccord.skill'),
        ),
        migrations.DeleteModel(
            name='CompanySize',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='EmploymentType',
        ),
        migrations.DeleteModel(
            name='ExperienceLevel',
        ),
        migrations.DeleteModel(
            name='JobTitle',
        ),
    ]
